# Generated by Django 6.0.6 on 2026-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('inspector', 'Inspector'), ('guest', 'Guest')], max_length=20),
        ),
    ]
