# Generated by Django 6.0.6 on 2026-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='construction_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('sales', 'Sales'), ('pre-construction', 'Pre-Construction'), ('construction', 'Construction'), ('completion', 'Completion'), ('maintenance', 'Maintenance')], max_length=20),
        ),
    ]
