# Generated by Django 6.0.6 on 2026-06-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobtemplate_jobtemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtemplate'),
        ),
    ]
