# Generated by Django 6.0.6 on 2026-06-26 23:06

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_client_email_job_client_name_job_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_reference',
            field=models.CharField(default=django.db.models.fields.UUIDField, max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
