# Generated by Django 6.0.6 on 2026-06-27 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_job_reference_alter_job_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
