# Generated by Django 6.0.6 on 2026-06-27 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_job_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
