# Generated by Django 6.0.6 on 2026-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('sales', 'Sales'), ('pre-construction', 'Pre-Construction'), ('construction', 'Construction'), ('completion', 'Completion'), ('maintenance', 'Maintenance')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('on_hold', 'ON_HOLD'), ('finalised', 'Finalised'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
