# Generated by Django 6.0.6 on 2026-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_stage_alter_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='client_name',
            new_name='client_first_name',
        ),
        migrations.AddField(
            model_name='job',
            name='client_billing',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
