# Generated by Django 6.0.6 on 2026-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_rename_client_name_job_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='client_billing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
