# Generated by Django 6.0.6 on 2026-09-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_client_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='access_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stage',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('pre-construction', 'Pre-Construction'), ('construction', 'Construction'), ('completion', 'Completion'), ('maintenance', 'Maintenance')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('on_hold', 'ON_HOLD'), ('finalised', 'Finalised'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
