# Generated by Django 6.0.6 on 2026-08-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_critical',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
