# Generated by Django 6.0.6 on 2026-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_critical_task_is_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Inpsection', 'Inpsection'), ('claim', 'Claim'), ('safety', 'Safety'), ('activity', 'Activity')], default='activity', max_length=20),
        ),
    ]
