# Generated by Django 6.0.6 on 2026-06-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectiontemplate'),
        ),
    ]
