# Generated by Django 6.0.6 on 2026-06-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_defect_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspection'),
        ),
    ]
